# ESLint 配置文件
env:
  browser: true     # 表示代码将在浏览器环境中运行
  es2021: true      # 启用对 ES2021 语法的支持

extends:
  - eslint:recommended                     # 使用 ESLint 推荐的规则
  - plugin:@typescript-eslint/recommended  # 使用 TypeScript 推荐的规则
  - plugin:react/recommended               # 使用 React 推荐的规则
  - plugin:prettier/recommended            # 这是 Prettier 插件推荐的一组规则，它做两件事：首先，它启用 eslint-plugin-prettier，使 Prettier 作为 ESLint 的一个插件运行，其次，它使用 eslint-config-prettier 来关闭所有可能与 Prettier 冲突的 ESLint 规则。

globals:
  process: readonly
  __dirname: readonly

parser: "@typescript-eslint/parser"   # 使用 @typescript-eslint/parser 解析器

parserOptions:
  ecmaVersion: "latest"   # 启用最新版本的 ECMAScript
  sourceType: module      # 使用模块化的代码

plugins:
  - "@typescript-eslint"   # 使用 @typescript-eslint 插件
  - react                 # 使用 React 插件

rules:
  indent:
    - off
  linebreak-style:
    - off
  quotes:
    - error
    - "single"
  semi:
    - error
    - "never"
  max-len:
    - error
    - 120
  typescript-eslint/no-explicit-any:
    - off
