# ESLint 配置文件
env:
  browser: true     # 表示代码将在浏览器环境中运行
  es2021: true      # 启用对 ES2021 语法的支持

globals:
  process: readonly # 声明全局变量 process 是只读的

extends:
  - eslint:recommended                     # 使用 ESLint 推荐的规则
  - plugin:@typescript-eslint/recommended  # 使用 TypeScript 推荐的规则
  - plugin:react/recommended               # 使用 React 推荐的规则

parser: "@typescript-eslint/parser"   # 使用 @typescript-eslint/parser 解析器

parserOptions:
  ecmaVersion: "latest"   # 启用最新版本的 ECMAScript
  sourceType: module      # 使用模块化的代码

plugins:
  - "@typescript-eslint"   # 使用 @typescript-eslint 插件
  - react                 # 使用 React 插件

rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - "windows"
  quotes:
    - error
    - "single"
  semi:
    - error
    - "never"
